---

 - name: Kill all iperf3 processes running 
   hosts: all
   gather_facts: false
   become: true 

   tasks:
   - name: list all iperf3 processes 
     shell: ps -eaf | grep iperf3 | sed -r 's/^[a-zA-Z0-9]+ +([0-9]+) +.*/\1/'
     register: output_ps 
     ignore_errors: true

   - debug:
       var: output_ps

   - name: kill all iperf3 processes in list
     shell: kill {{ item }}
     with_items: output_ps

