---
 - name: Execute the given command and provide stdout 
   hosts: all
   gather_facts: false
   become: true 

   vars:
     traffic_send_port: 5201
     traffic_rev_port: 5202

   tasks:
   - name: lxd execute - spawn iperf3 SEND server command
     shell: lxc exec {{ traffic_instance_name }} -- bash -c "iperf3 -B {{ traffic_engine_int_ip }} -p {{ traffic_send_port }} -s &"
     async: 10000
     poll: 0
     register: output_send 
     ignore_errors: true

   - name: lxd execut - spawn iperf3 REV server command
     shell: lxc exec {{ traffic_instance_name }} -- bash -c "iperf3 -B {{ traffic_engine_int_ip }} -p {{ traffic_rev_port }} -s &" 
     async: 10000
     poll: 0
     register: output_rev
     ignore_errors: true

   - debug:
       var: output_send

   - debug:
       var: output_rev


