---
 - name: Execute the given command and provide stdout 
   hosts: all
   gather_facts: false
   become: true

   vars:
     traffic_port: 5201

   tasks:
   - name: execute iperf3 server command
     raw: iperf3 -B {{ address }} -p {{ traffic_port }} -s -D
     register: command_output 

   - debug:
       var: command_output

