---

 - name: Kill all iperf3 processes running 
   hosts: all
   gather_facts: false
   become: true 

   tasks:
   - name: list all iperf3 processes 
     shell: >
        ps -eaf |
        grep iperf3 |
        awk '//{print $2}' 
     register: output_ps 
     ignore_errors: true

   - debug:
       var: output_ps

   - name: kill all iperf3 processes in list
     shell: kill {{ item | int }}
     with_items: "{{ output_ps.stdout_lines }}"
     ignore_errors: true

