---
 - name: Configure BGP for LXD traffic container 
   hosts: all
   gather_facts: false

   tasks: 
   - name: Copy daemons file to lxd container
     copy:
       src: files/bgp_lxd_daemons
       dest: /var/lib/lxd/containers/{{ container_name }}/rootfs/etc/frr/daemons
     become: yes
  
   - name: Splice BGP configuration into frr.conf
     blockinfile:
        path: /var/lib/lxd/containers/{{ container_name }}/rootfs/etc/frr/frr.conf
        block: |
            router bgp {{ bgp_asn_prov }}
              bgp router-id {{ bgp_router_id }} 
              no bgp default ipv4-unicast
              bgp default show-hostname
              neighbor {{ cloud_gw_ip }} remote-as {{ bgp_asn_cloud }}
              !
              address-family ipv4 unicast
                network {{ bgp_router_id }}/32
                neighbor {{ cloud_gw_ip }} activate
                neighbor {{ cloud_gw_ip }} soft-reconfiguration inbound
                neighbor {{ cloud_gw_ip }} allowas-in
                neighbor {{ cloud_gw_ip }} password somekindofpassword
              exit-address-family
        insertafter: '^username*'
     become: yes
  
   - name: Restart LXD container
     command: lxc restart {{ container_name }}
